variable "region" {
  description = "AWS region for the demo environment."
  type        = string
  default     = "us-east-1"
}

variable "name" {
  description = "Name prefix applied to all resources."
  type        = string
  default     = "harnessflow"
}

variable "environment" {
  description = "Environment tag."
  type        = string
  default     = "demo"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "kubernetes_version" {
  description = "EKS control-plane version."
  type        = string
  default     = "1.31"
}

variable "node_instance_type" {
  description = "EC2 instance type for the single managed node group."
  type        = string
  default     = "t3.medium"
}

variable "node_desired_size" {
  description = "Desired node count."
  type        = number
  default     = 2
}

variable "node_min_size" {
  description = "Minimum node count."
  type        = number
  default     = 1
}

variable "node_max_size" {
  description = "Maximum node count (cluster-autoscaler / Karpenter ceiling)."
  type        = number
  default     = 4
}

variable "postgres_instance_class" {
  description = "RDS instance class. db.t4g.small is the cheapest Graviton burstable that fits the demo."
  type        = string
  default     = "db.t4g.small"
}

variable "postgres_allocated_storage" {
  description = "RDS allocated storage (GiB)."
  type        = number
  default     = 20
}

variable "postgres_version" {
  description = "RDS Postgres engine version."
  type        = string
  default     = "16.4"
}

variable "redis_node_type" {
  description = "ElastiCache node type. cache.t4g.micro is the cheapest that exists."
  type        = string
  default     = "cache.t4g.micro"
}

variable "db_username" {
  description = "Master username for RDS Postgres."
  type        = string
  default     = "harnessflow"
}

# The DB password is generated by Terraform (random_password) and stored in
# Secrets Manager — never set as a plaintext variable. See rds.tf.

variable "tags" {
  description = "Extra tags merged onto every resource."
  type        = map(string)
  default     = {}
}
