// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Workflow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Version     int32              `db:"version" json:"version"`
	Description string             `db:"description" json:"description"`
	YamlSource  string             `db:"yaml_source" json:"yaml_source"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorkflowRun struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	WorkflowID         pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	TemporalWorkflowID string             `db:"temporal_workflow_id" json:"temporal_workflow_id"`
	Status             string             `db:"status" json:"status"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt            pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	TraceID            string             `db:"trace_id" json:"trace_id"`
	TotalCostUsdCents  int64              `db:"total_cost_usd_cents" json:"total_cost_usd_cents"`
	TotalTokens        int64              `db:"total_tokens" json:"total_tokens"`
	Error              string             `db:"error" json:"error"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WorkflowStep struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	RunID         pgtype.UUID        `db:"run_id" json:"run_id"`
	Name          string             `db:"name" json:"name"`
	Type          string             `db:"type" json:"type"`
	Status        string             `db:"status" json:"status"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt       pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	LatencyMs     int64              `db:"latency_ms" json:"latency_ms"`
	InputTokens   int64              `db:"input_tokens" json:"input_tokens"`
	OutputTokens  int64              `db:"output_tokens" json:"output_tokens"`
	CostUsdCents  int64              `db:"cost_usd_cents" json:"cost_usd_cents"`
	Attempt       int32              `db:"attempt" json:"attempt"`
	Error         string             `db:"error" json:"error"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	InputPreview  string             `db:"input_preview" json:"input_preview"`
	OutputPreview string             `db:"output_preview" json:"output_preview"`
}
