// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountWorkflows(ctx context.Context) (int64, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error)
	CreateStep(ctx context.Context, arg CreateStepParams) (WorkflowStep, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	GetLatestWorkflowVersion(ctx context.Context, name string) (Workflow, error)
	GetRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error)
	GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]WorkflowRun, error)
	ListRunsByWorkflow(ctx context.Context, arg ListRunsByWorkflowParams) ([]WorkflowRun, error)
	ListStepsByRun(ctx context.Context, runID pgtype.UUID) ([]WorkflowStep, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	UpdateStepStatus(ctx context.Context, arg UpdateStepStatusParams) error
	UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) error
}

var _ Querier = (*Queries)(nil)
