// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO workflow_runs (id, workflow_id, temporal_workflow_id, status, trace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, temporal_workflow_id, status, started_at, ended_at, trace_id, total_cost_usd_cents, total_tokens, error, created_at
`

type CreateRunParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	WorkflowID         pgtype.UUID `db:"workflow_id" json:"workflow_id"`
	TemporalWorkflowID string      `db:"temporal_workflow_id" json:"temporal_workflow_id"`
	Status             string      `db:"status" json:"status"`
	TraceID            string      `db:"trace_id" json:"trace_id"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.WorkflowID,
		arg.TemporalWorkflowID,
		arg.Status,
		arg.TraceID,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TraceID,
		&i.TotalCostUsdCents,
		&i.TotalTokens,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createStep = `-- name: CreateStep :one
INSERT INTO workflow_steps (id, run_id, name, type, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, name, type, status, started_at, ended_at, latency_ms, input_tokens, output_tokens, cost_usd_cents, attempt, error, created_at, input_preview, output_preview
`

type CreateStepParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	RunID  pgtype.UUID `db:"run_id" json:"run_id"`
	Name   string      `db:"name" json:"name"`
	Type   string      `db:"type" json:"type"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (WorkflowStep, error) {
	row := q.db.QueryRow(ctx, createStep,
		arg.ID,
		arg.RunID,
		arg.Name,
		arg.Type,
		arg.Status,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsdCents,
		&i.Attempt,
		&i.Error,
		&i.CreatedAt,
		&i.InputPreview,
		&i.OutputPreview,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, workflow_id, temporal_workflow_id, status, started_at, ended_at, trace_id, total_cost_usd_cents, total_tokens, error, created_at FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TraceID,
		&i.TotalCostUsdCents,
		&i.TotalTokens,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, workflow_id, temporal_workflow_id, status, started_at, ended_at, trace_id, total_cost_usd_cents, total_tokens, error, created_at FROM workflow_runs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListRunsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TemporalWorkflowID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.TraceID,
			&i.TotalCostUsdCents,
			&i.TotalTokens,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByWorkflow = `-- name: ListRunsByWorkflow :many
SELECT id, workflow_id, temporal_workflow_id, status, started_at, ended_at, trace_id, total_cost_usd_cents, total_tokens, error, created_at FROM workflow_runs
WHERE workflow_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRunsByWorkflowParams struct {
	WorkflowID pgtype.UUID `db:"workflow_id" json:"workflow_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListRunsByWorkflow(ctx context.Context, arg ListRunsByWorkflowParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listRunsByWorkflow, arg.WorkflowID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TemporalWorkflowID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.TraceID,
			&i.TotalCostUsdCents,
			&i.TotalTokens,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByRun = `-- name: ListStepsByRun :many
SELECT id, run_id, name, type, status, started_at, ended_at, latency_ms, input_tokens, output_tokens, cost_usd_cents, attempt, error, created_at, input_preview, output_preview FROM workflow_steps
WHERE run_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListStepsByRun(ctx context.Context, runID pgtype.UUID) ([]WorkflowStep, error) {
	rows, err := q.db.Query(ctx, listStepsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStep
	for rows.Next() {
		var i WorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.LatencyMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsdCents,
			&i.Attempt,
			&i.Error,
			&i.CreatedAt,
			&i.InputPreview,
			&i.OutputPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE workflow_runs
SET status = $2,
    started_at = COALESCE(started_at, $3),
    ended_at = $4,
    error = $5
WHERE id = $1
`

type UpdateRunStatusParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Status    string             `db:"status" json:"status"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	Error     string             `db:"error" json:"error"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.Error,
	)
	return err
}

const updateStepStatus = `-- name: UpdateStepStatus :exec
UPDATE workflow_steps
SET status = $2,
    started_at = COALESCE(started_at, $3),
    ended_at = $4,
    latency_ms = $5,
    error = $6
WHERE id = $1
`

type UpdateStepStatusParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Status    string             `db:"status" json:"status"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	LatencyMs int64              `db:"latency_ms" json:"latency_ms"`
	Error     string             `db:"error" json:"error"`
}

func (q *Queries) UpdateStepStatus(ctx context.Context, arg UpdateStepStatusParams) error {
	_, err := q.db.Exec(ctx, updateStepStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.LatencyMs,
		arg.Error,
	)
	return err
}
