// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkflows = `-- name: CountWorkflows :one
SELECT COUNT(*) FROM workflows
`

func (q *Queries) CountWorkflows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (id, name, version, description, yaml_source, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, version, description, yaml_source, status, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Version     int32       `db:"version" json:"version"`
	Description string      `db:"description" json:"description"`
	YamlSource  string      `db:"yaml_source" json:"yaml_source"`
	Status      string      `db:"status" json:"status"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.YamlSource,
		arg.Status,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.YamlSource,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestWorkflowVersion = `-- name: GetLatestWorkflowVersion :one
SELECT id, name, version, description, yaml_source, status, created_at, updated_at FROM workflows
WHERE name = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestWorkflowVersion(ctx context.Context, name string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersion, name)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.YamlSource,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, version, description, yaml_source, status, created_at, updated_at FROM workflows WHERE id = $1
`

func (q *Queries) GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.YamlSource,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, version, description, yaml_source, status, created_at, updated_at FROM workflows
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListWorkflowsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.YamlSource,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowStatus = `-- name: UpdateWorkflowStatus :exec
UPDATE workflows
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateWorkflowStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowStatus, arg.ID, arg.Status)
	return err
}
